### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by alexanderisora** [phpbb-de/phpbb-ext-newsletter#9]
Hello! I've installed the extension on my phpbb v3.2 forum. But how to use it? 🤔

**Comment by Crizz0** [comment]
In the ucp.php is an option for the users, if they  like to have the newsletter or not. In the acp, where you can send mass emails, you can tick a checkbox to send the mail as a newsletter.

Remember to change the mail footer in the language files of the extensions. And use it on your own risk, it is not yet released.

Regards

**Comment by alexanderisora** [comment]
@Crizz0 thanks for the quick reply!
And what is the difference between a newsletter and a mass email? 🤔

**Comment by Crizz0** [comment]
The newsletter has a few differences in the mail  appearance and is only sent to people who have ticked the option in the ucp.
